_nb_ext_conf              0.3.0                    py27_0  
anaconda-client           1.5.1                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.4                      py27_0  
biopython                 1.67                np111py27_0  
cairo                     1.12.18                       6  
cloog                     0.18.0                        0  
clyent                    1.2.2                    py27_0  
configparser              3.5.0                    py27_0  
curl                      7.49.0                        1  
cycler                    0.10.0                   py27_0  
decorator                 4.0.10                   py27_0  
entrypoints               0.2.2                    py27_0  
fontconfig                2.11.1                        6  
freetype                  2.5.5                         1  
functools32               3.2.3.2                  py27_0  
get_terminal_size         1.0.0                    py27_0  
glib                      2.43.0                        1  
gmp                       5.1.2                         2  
h5py                      2.6.0               np111py27_2  
harfbuzz                  0.9.39                        1  
hdf5                      1.8.17                        1  
bcftools                  1.3.1                         0    https://conda.binstar.org/bioconda
gimmemotifs               0.9.0.6                  py27_0    https://conda.binstar.org/bioconda
htslib                    1.3.1                         0    https://conda.binstar.org/bioconda
kid                       0.9.6                    py27_1    https://conda.binstar.org/bioconda
lightning                 0.2.dev0                 py27_0    https://conda.binstar.org/bioconda
moods                     1.9.0                    py27_0    https://conda.binstar.org/bioconda
pybedtools                0.7.7                    py27_1    https://conda.binstar.org/bioconda
pybigwig                  0.2.8                    py27_0    https://conda.binstar.org/bioconda
pysam                     0.9.1                    py27_0    https://conda.binstar.org/bioconda
samtools                  1.3.1                         1    https://conda.binstar.org/bioconda
ucsc-genepredtobed        332                           0    https://conda.binstar.org/bioconda
ipykernel                 4.4.1                    py27_0  
ipython                   5.1.0                    py27_0  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                5.2.2                    py27_0  
isl                       0.12.2                        0  
jinja2                    2.8                      py27_1  
jsonschema                2.5.1                    py27_0  
jupyter                   1.0.0                    py27_3  
jupyter_client            4.3.0                    py27_0  
jupyter_console           5.0.0                    py27_0  
jupyter_core              4.1.1                    py27_0  
libffi                    3.2.1                         0  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libpng                    1.6.22                        0  
libsodium                 1.0.10                        0  
libxml2                   2.9.2                         0  
markupsafe                0.23                     py27_2  
matplotlib                1.5.1               np111py27_0  
mistune                   0.7.2                    py27_0  
mkl                       11.3.3                        0  
mpc                       1.0.1                         0  
mpfr                      3.1.2                         0  
mysql                     5.5.24                        0  
nb_anacondacloud          1.2.0                    py27_0  
nb_conda                  2.0.0                    py27_0  
nb_conda_kernels          2.0.0                    py27_0  
nbconvert                 4.2.0                    py27_0  
nbformat                  4.1.0                    py27_0  
nbpresent                 3.0.2                    py27_0  
ncurses                   5.9                           8  
notebook                  4.2.2                    py27_0  
numexpr                   2.6.1               np111py27_0  
numpy                     1.11.1                   py27_0  
openssl                   1.0.2h                        1  
pandas                    0.18.1              np111py27_0  
pango                     1.39.0                        1  
path.py                   8.2.1                    py27_0  
pathlib2                  2.1.0                    py27_0  
patsy                     0.4.1                    py27_0  
pexpect                   4.0.1                    py27_0  
pickleshare               0.7.3                    py27_0  
pip                       8.1.2                    py27_0  
pixman                    0.32.6                        0  
prompt_toolkit            1.0.3                    py27_0  
ptyprocess                0.5.1                    py27_0  
pycairo                   1.10.0                   py27_0  
pygments                  2.1.3                    py27_0  
pymc                      2.3.6               np111py27_2  
pyparsing                 2.1.4                    py27_0  
pyqt                      4.11.4                   py27_4  
pytables                  3.2.3.1             np111py27_0  
python                    2.7.12                        1  
python-dateutil           2.5.3                    py27_0  
pytz                      2016.6.1                 py27_0  
pyyaml                    3.11                     py27_4  
pyzmq                     15.4.0                   py27_0  
qt                        4.8.7                         4  
qtconsole                 4.2.1                    py27_0  
readline                  6.2                           2  
requests                  2.11.1                   py27_0  
scikit-learn              0.17.1              np111py27_2  
scipy                     0.18.0              np111py27_0  
seaborn                   0.7.1                    py27_0  
setuptools                26.1.1                   py27_0  
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
statsmodels               0.6.1               np111py27_1  
terminado                 0.6                      py27_0  
tk                        8.5.18                        0  
tornado                   4.4.1                    py27_0  
traitlets                 4.2.2                    py27_0  
wcwidth                   0.1.7                    py27_0  
wheel                     0.29.0                   py27_0  
widgetsnbextension        1.2.6                    py27_0  
xgboost                   0.60                     py27_0    https://conda.binstar.org/creditx/linux-64/xgboost-0.60-py27_0.tar.bz2
yaml                      0.1.6                         0  
zeromq                    4.1.4                         0  
zlib                      1.2.8                         3 
